version: '3.6'

services:
    api:
        container_name: harvard-arts-reverse-proxy
        restart: always
        build: .
        ports:
            - 80:4000
        volumes:
            - ./:/go/src/github.com/harvard-arts-reverse-proxy